 route:
     receiver: 'slack'

 receivers:
     - name: 'slack'
       slack_configs:
           - send_resolved: true
             username: 'prom'
             channel: '#sys-admins'
             api_url: 'https://hooks.slack.com/services/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'
